garden_management/authentication/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = "authentication"

urlpatterns = [
    # /authenticationにアクセスした場合は、ログインページにリダイレクト。
    path("", RedirectView.as_view(url="/authentication/login")),
    # ユーザ登録
    path("signup", views.SignUpView.as_view(), name="signup"),
    # ログイン
    path("login", views.CustomLoginView.as_view(), name="login"),
    # ログアウト
    path("logout", views.CustomLogoutView.as_view(), name="logout"),
    # ユーザ情報
    path(
        "user-information",
        views.UserInformationView.as_view(),
        name="user-information"
    ),
    # ユーザ情報編集画面
    path(
        "user-information/edit/<int:pk>",
        views.UserInformationEditView.as_view(),
        name="user-information-edit"
    ),
    # パスワード変更
    path(
        "password-change",
        views.CustomPasswordChangeView.as_view(),
        name="password-change"
    ),
    # パスワード変更完了画面
    path(
        "password-change/done",
        views.CustomPasswordChangeDoneView.as_view(),
        name="password-change-done"
    ),
    # パスワードリセット用メール送信画面
    path(
        "password-reset",
        views.CustomPasswordResetView.as_view(),
        name="password-reset"
    ),
    # パスワードリセット用メール送信後画面
    path(
        "password-reset/done",
        views.CustomPasswordResetDoneView.as_view(),
        name="password-reset-done"
    ),
    # パスワードリセットフォーム画面
    path(
        "password-reset/comfirm/<uidb64>/<token>",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password-reset-confirm"
    ),
    # パスワードリセット完了画面
    path(
        "password-reset/complete",
        views.CustomPasswordResetCompleteView.as_view(),
        name="password-reset-complete"
    )
]

garden_management/garden_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView

# MEDIA関連
from .settings import DEBUG, MEDIA_URL, MEDIA_ROOT
from django.contrib.staticfiles.urls import static


urlpatterns = [
    path("admin/", admin.site.urls),
    # PWA
    path(
        "sw.js", (
            TemplateView.as_view(
                template_name="sw.js", content_type="application/javascript"
            )
        ),
        name="sw.js"
    ),
    path("", RedirectView.as_view(url="/authentication/login")),
    path("authentication/", include("authentication.urls")),
    path("plant-management/", include("plant_management.urls")),
    path("help/", include("help.urls")),
]

# "settings.py"で"DEBUG=True"時のMEDIA（画像配信）の設定
if DEBUG:
    urlpatterns += static(
        MEDIA_URL, document_root=MEDIA_ROOT
    )

garden_management/help/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = "help"

urlpatterns = [
    # /helpにアクセスした場合は、お問い合わせページにリダイレクト。
    path("", RedirectView.as_view(url="/help/inquiry")),
    # 問い合わせ
    path("inquiry", views.InquiryFormView.as_view(), name="inquiry"),
    # 問い合わせ完了
    path(
        "inquiry-complete",
        views.InquiryCompleteView.as_view(),
        name="inquiry-complete"
    )
]

garden_management/plant_management/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = "plant_management"

urlpatterns = [
    # /plant-managementにアクセスした場合は、一覧ページにリダイレクト。
    path("", RedirectView.as_view(url="/plant-management/list")),
    # 植物一覧
    path("list", views.PlantListView.as_view(), name="list"),
    # 水やり完了
    path(
        "watering-complete/<int:pk>",
        views.complete_watering,
        name="watering-complete"
    ),
    # 植物詳細
    path("detail/<int:pk>", views.PlantDetailView.as_view(), name="detail"),
    # 植物追加
    path("add", views.PlantAddView.as_view(), name="add"),
    # 植物編集
    path("edit/<int:pk>", views.PlantEditView.as_view(), name="edit"),
    # 植物削除
    path("delete/<int:pk>", views.PlantDeleteView.as_view(), name="delete"),
    # 関連url追加
    path(
        "add-url/<int:plant_id>",
        views.RelatedUrlAddView.as_view(),
        name="add-url"
    ),
    # 関連url削除
    path(
        "delete-url/<int:pk>",
        views.RelatedUrlDeleteView.as_view(),
        name="delete-url"
    )
]

garden_management/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8" />
    <meta name="robots" content="noindex" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/sanitize.css' %}">
    <link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/bulma.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>{% block title %}にわかん - {% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon" />
    <!-- PWA -->
    <link rel="manifest" href="{% static 'pwa/manifest.json' %}" />
    <script>
        if ("serviceWorker" in navigator) {
            window.addEventListener("load", function () {
                navigator.serviceWorker.register("{% url 'sw.js' %}").then(
                    function (registration) {
                        // Registration was successful
                        console.log(
                            "ServiceWorker registration successful with scope: ",
                            registration.scope
                        );
                    },
                    function (err) {
                        // registration failed :(
                        console.log(
                            "ServiceWorker registration failed: ",
                            err
                        );
                    }
                );
            });
        }
    </script>
    <!-- END PWA -->
    {% block head %}
    {% endblock %}
</head>

<body class="has-navbar-fixed-top">
    <!-- header -->
    <header>
        <nav class="navbar is-primary is-fixed-top">
            <div class="navbar-brand">
                <a href="{% url 'plant_management:list' %}" class="navbar-item px-2 py-0">
                    <img src="{% static 'img/logotype-transparent.png' %}" alt="にわかんのロゴタイプ。" class="logo-type">
                </a>
                {% if user.is_authenticated %}
                <div class="navbar-burger" data-target="navbarExampleTransparentExample">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
                {% endif %}
            </div>
            {% if user.is_authenticated %}
            <!-- navigation menu -->
            <div id="navbarExampleTransparentExample" class="navbar-menu">
                <div class="navbar-start">
                    <a href="{% url 'plant_management:list' %}" class="navbar-item icon-text">
                        <span class="icon">
                            <i class="far fa-list-alt"></i>
                        </span>
                        <span>
                            植物一覧
                        </span>
                    </a>
                    <a href="{% url 'plant_management:add' %}" class="navbar-item icon-text">
                        <span class="icon">
                            <i class="far fa-plus-square"></i>
                        </span>
                        <span>
                            植物追加
                        </span>
                    </a>
                    <!-- other dropdown -->
                    <div class="navbar-item has-dropdown is-hoverable">
                        <p class="navbar-link">
                            <span>その他</span>
                        </p>
                        <div class="navbar-dropdown is-boxed">
                            <!-- FAのアイコンのところで改行されないように、15文字(15em)文のwidthを持つ要素を挿入。 -->
                            <span class="navbar-item p-0" style="width:15em;"></span>
                            <a class="navbar-item icon-text pr-0" href="{% url 'help:inquiry' %}">
                                <span class="icon">
                                    <i class="fas fa-comments"></i>
                                </span>
                                <span>
                                    お問い合わせ
                                </span>
                            </a>
                            <hr class="navbar-divider">
                            <a class="navbar-item icon-text pr-0" href="#">
                                <span class="icon">
                                    <i class="fas fa-info-circle"></i>
                                </span>
                                <span>
                                    このアプリについて(未)
                                </span>
                            </a>
                            <a class="navbar-item icon-text pr-0"
                                href="https://github.com/AikawaShota/garden-management" target="_blank"
                                rel="noopener noreferrer">
                                <span class="icon">
                                    <i class="fab fa-github"></i>
                                </span>
                                <span>
                                    ソースコード
                                </span>
                            </a>
                        </div>
                    </div>
                    <!-- END other dropdown -->
                </div>
                <div class="navbar-end">
                    <!-- user dropdown -->
                    <div class="navbar-item has-dropdown is-hoverable">
                        <p class="navbar-link icon-text">
                            <span class="icon mt-1 mr-0">
                                <i class="fas fa-user"></i>
                            </span>
                            <span>ユーザー</span>
                        </p>
                        <div class="navbar-dropdown is-boxed">
                            <a class="navbar-item icon-text pr-0" href="{% url 'authentication:user-information' %}">
                                <span class="icon">
                                    <i class="fas fa-user-edit"></i>
                                </span>
                                <span>
                                    ユーザ情報
                                </span>
                            </a>
                            <a class="navbar-item icon-text pr-0" href="{% url 'authentication:logout' %}">
                                <span class="icon">
                                    <i class="fas fa-sign-out-alt"></i>
                                </span>
                                <span>
                                    ログアウト
                                </span>
                            </a>
                        </div>
                    </div>
                    <!-- END user dropdown -->
                </div>
            </div>
            <!-- END navigation menu -->
            {% endif %}
        </nav>
    </header>
    <!-- END header-->

    <!-- main -->
    <main>
        {% block main %}
        {% endblock %}
    </main>
    <!-- END main -->

    <!-- footer -->
    <footer class="footer has-background-primary">
        <div class="content has-text-centered has-text-warning-light">
            <p>&copy; 2023 Aikawa Shota.</p>
        </div>
    </footer>
    <!-- END footer -->
</body>

<script src="{% static 'js/scripts.js' %}"></script>
{% block scripts %}
{% endblock %}

</html>