garden_management/authentication/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = "authentication"

urlpatterns = [
    # /authenticationにアクセスした場合は、ログインページにリダイレクト。
    path("", RedirectView.as_view(url="/authentication/login")),
    # ユーザ登録
    path("signup", views.SignUpView.as_view(), name="signup"),
    # ログイン
    path("login", views.CustomLoginView.as_view(), name="login"),
    # ログアウト
    path("logout", views.CustomLogoutView.as_view(), name="logout"),
    # ユーザ情報
    path(
        "user-information",
        views.UserInformationView.as_view(),
        name="user-information"
    ),
    # ユーザ情報編集画面
    path(
        "user-information/edit/<int:pk>",
        views.UserInformationEditView.as_view(),
        name="user-information-edit"
    ),
    # パスワード変更
    path(
        "password-change",
        views.CustomPasswordChangeView.as_view(),
        name="password-change"
    ),
    # パスワード変更完了画面
    path(
        "password-change/done",
        views.CustomPasswordChangeDoneView.as_view(),
        name="password-change-done"
    ),
    # パスワードリセット用メール送信画面
    path(
        "password-reset",
        views.CustomPasswordResetView.as_view(),
        name="password-reset"
    ),
    # パスワードリセット用メール送信後画面
    path(
        "password-reset/done",
        views.CustomPasswordResetDoneView.as_view(),
        name="password-reset-done"
    ),
    # パスワードリセットフォーム画面
    path(
        "password-reset/comfirm/<uidb64>/<token>",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password-reset-confirm"
    ),
    # パスワードリセット完了画面
    path(
        "password-reset/complete",
        views.CustomPasswordResetCompleteView.as_view(),
        name="password-reset-complete"
    )
]

garden_management/garden_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView

# MEDIA関連
from .settings import DEBUG, MEDIA_URL, MEDIA_ROOT
from django.contrib.staticfiles.urls import static


urlpatterns = [
    path("admin/", admin.site.urls),
    # PWA
    path(
        "sw.js", (
            TemplateView.as_view(
                template_name="sw.js", content_type="application/javascript"
            )
        ),
        name="sw.js"
    ),
    path("", RedirectView.as_view(url="/authentication/login")),
    path("authentication/", include("authentication.urls")),
    path("plant-management/", include("plant_management.urls")),
    path("help/", include("help.urls")),
]

# "settings.py"で"DEBUG=True"時のMEDIA（画像配信）の設定
if DEBUG:
    urlpatterns += static(
        MEDIA_URL, document_root=MEDIA_ROOT
    )

garden_management/help/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = "help"

urlpatterns = [
    # /helpにアクセスした場合は、お問い合わせページにリダイレクト。
    path("", RedirectView.as_view(url="/help/inquiry")),
    # 問い合わせ
    path("inquiry", views.InquiryFormView.as_view(), name="inquiry"),
    # 問い合わせ完了
    path(
        "inquiry-complete",
        views.InquiryCompleteView.as_view(),
        name="inquiry-complete"
    )
]

garden_management/plant_management/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = "plant_management"

urlpatterns = [
    # /plant-managementにアクセスした場合は、一覧ページにリダイレクト。
    path("", RedirectView.as_view(url="/plant-management/list")),
    # 植物一覧
    path("list", views.PlantListView.as_view(), name="list"),
    # 水やり完了
    path(
        "watering-complete/<int:pk>",
        views.complete_watering,
        name="watering-complete"
    ),
    # 植物詳細
    path("detail/<int:pk>", views.PlantDetailView.as_view(), name="detail"),
    # 植物追加
    path("add", views.PlantAddView.as_view(), name="add"),
    # 植物編集
    path("edit/<int:pk>", views.PlantEditView.as_view(), name="edit"),
    # 植物削除
    path("delete/<int:pk>", views.PlantDeleteView.as_view(), name="delete"),
    # 関連url追加
    path(
        "add-url/<int:plant_id>",
        views.RelatedUrlAddView.as_view(),
        name="add-url"
    ),
    # 関連url削除
    path(
        "delete-url/<int:pk>",
        views.RelatedUrlDeleteView.as_view(),
        name="delete-url"
    )
]

garden_management/authentication/forms.py
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
    UsernameField,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm
)
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import password_validation, get_user_model
from django import forms

CustomUserModel = get_user_model()


# ユーザ登録フォーム
class SignUpForm(UserCreationForm):
    class Meta:
        model = CustomUserModel
        fields = ("email", "password1", "password2", "nickname")

    email = forms.EmailField(
        required=True,
        max_length=254,
        widget=forms.EmailInput(
            attrs={
                "autocomplete": "email",
                "placeholder": "sample@example.com",
                "class": "input"
            }
        )
    )

    password1 = forms.CharField(
        required=True,
        max_length=255,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "class": "input"
            }
        )
    )

    password2 = forms.CharField(
        required=True,
        max_length=255,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "class": "input"
            }
        )
    )

    nickname = forms.CharField(
        required=True,
        max_length=127,
        widget=forms.TextInput(
            attrs={
                "autocomplete": "nickname",
                "placeholder": "nickname",
                "class": "input"
            }
        )
    )


# ログインフォーム
class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

    username = UsernameField(
        required=True,
        max_length=254,
        widget=forms.EmailInput(
            attrs={
                "autocomplete": "email",
                "placeholder": "sample@example.com",
                "class": "input"
            }
        )
    )

    password = forms.CharField(
        required=True,
        max_length=255,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "class": "input"
            }
        )
    )


# パスワード変更フォーム
class CustomPasswordChangeForm(PasswordChangeForm):
    # 継承元のPasswordChangeFormのfieldをオーバーライド。
    old_password = forms.CharField(
        label=_("Old password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "autofocus": True,
                "class": "input",
            }
        ),
    )

    # 継承元のPasswordChangeFormが継承しているSetPasswordFormのfiledをオーバーライド。
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "class": "input",
            }
        ),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )

    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "class": "input",
            }
        ),
    )


# パスワードリセット用メール送信用メールアドレス入力フォーム
class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        max_length=254,
        widget=forms.EmailInput(
            attrs={
                "autocomplete": "email",
                "placeholder": "sample@example.com",
                "class": "input"
            }
        )
    )


# パスワードリセット用パスワード入力フォーム
class CustomPasswordSetForm(SetPasswordForm):
    new_password1 = forms.CharField(
        max_length=255,
        label=_("New password"),
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "class": "input"
            }
        ),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )

    new_password2 = forms.CharField(
        max_length=255,
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "class": "input"
            }
        ),
    )


# ユーザ情報編集フォーム
class UserInformationEditForm(forms.ModelForm):
    class Meta:
        model = CustomUserModel
        fields = (
            "nickname",
            "email"
        )

    nickname = forms.CharField(
        max_length=127,
        widget=forms.TextInput(
            attrs={
                "class": "input",
                "placeholder": "nickname",
                "autocomplete": "nickname"
            }
        )
    )

    email = forms.EmailField(
        max_length=254,
        widget=forms.EmailInput(
            attrs={
                "class": "input",
                "placeholder": "sample@example.com",
                "autocomplete": "email"
            }
        )
    )

garden_management/authentication/views.py
from . import forms
from utilities.mixins import LoginUserOnlyMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView
from django.contrib.auth import login, authenticate, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)


# ユーザ登録
class SignUpView(CreateView):
    """ユーザ登録を行うView。

    CreateViewを継承し、ユーザモデルにユーザを新規登録します。

    Note:
        form_valid内で、正しくユーザ登録が行われた場合に自動的にログインする処理を行っています。
        ログイン後はsuccess_urlに格納されているurlに遷移します。

    Attributes:
        form_class(obj): ユーザ登録に利用するFormを格納します。
        template_name(str): ユーザ登録に利用するtemplateまでのパスを格納します。
        success_url(str): ユーザ登録処理が正常に終了した場合の遷移先URLを格納します。
    """

    form_class = forms.SignUpForm
    template_name = "authentication/signup.html"
    success_url = reverse_lazy("plant_management:list")

    def form_valid(self, form):
        # 継承元のform_validを呼び出してuserを保存するための返り値を取得。
        response = super().form_valid(form)
        email = form.cleaned_data["email"]
        password = form.cleaned_data["password1"]
        # authenticate関数はusernameとpassword認証が行い、有効だった場合はUserオブジェクトを返す。
        user = authenticate(
            request=self.request, username=email, password=password
        )
        # userオブジェクトがNoneかどうかの判定。
        if user is not None:
            # login関数でユーザをログインさせる。
            login(self.request, user)
        else:
            # userオブジェクトがNoneの場合の処理。
            pass
        return response


# ログイン
class CustomLoginView(LoginView):
    """ログインフォームの表示とログイン処理を行うView。

    LoginViewを継承し、ログイン処理を行っています。

    Attributes:
        template_name(str): ユーザ登録に利用するtemplateまでのパスを格納します。
        authentication_form(obj): ログイン時に利用するFormを指定します。
    """
    template_name = "authentication/login.html"
    authentication_form = forms.LoginForm


# ログアウト
class CustomLogoutView(LogoutView):
    """ログアウト処理を行うView。

    LogoutViewを継承し、ログアウト処理を行っています。

    Attributes:
        template_name(str): ログアウト時に利用するtemplateまでのパスを格納します。
        next_page(str): ログアウト処理が完了した際の遷移先を指定します。
    """
    template_name = "authentication/logout.html"
    next_page = "authentication:logout"


# ユーザ情報表示
class UserInformationView(LoginRequiredMixin, TemplateView):
    """ユーザ情報の表示をするView。

    TemplateViewを継承し、templateを指定しています。

    Note:
        LoginRequiredMixinを継承しているため、ログイン時のみアクセス可能です。
        ユーザ情報の取得・表示はtemplate側で行っています。
    Attributes:
        template_name(str): ユーザ情報表示に利用するtemplateまでのパスを格納します。
    """
    template_name = "authentication/user_information.html"


# ユーザ情報編集
class UserInformationEditView(
    LoginUserOnlyMixin,
    LoginRequiredMixin,
    UpdateView
):
    """ユーザ情報の編集を行うView。

    UpdateViewを継承し、ユーザモデルの該当オブジェクトの情報を更新します。

    Note:
        ログイン中のユーザではないユーザ情報が編集できないよう、LoginUserOnlyMixinを継承しています。

    Attributes:
        template_name(str): ユーザ情報編集に利用するtemplateまでのパスを格納します。
        form_class(obj): ユーザ情報編集に利用するFormを格納します。
        model(obj): 更新するモデル(ユーザモデル)を指定します。
        success_url(str): ユーザ情報の更新が成功した場合の遷移先URLを格納します。
    """
    template_name = "authentication/user_information_edit.html"
    form_class = forms.UserInformationEditForm
    model = get_user_model()
    success_url = reverse_lazy("authentication:user-information")


# パスワード変更
class CustomPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    """パスワード変更を行うView。

    PasswordChangeViewを継承し、パスワード変更処理を行います。

    Attributes:
        form_class(obj): パスワード変更に利用するFormを指定します。
        template_name(str): パスワード変更に利用するtemplateまでのパスを格納します。
        success_url(str): パスワード変更処理が成功した場合の遷移先URLを格納します。
    """
    form_class = forms.CustomPasswordChangeForm
    template_name = "authentication/password_change.html"
    success_url = reverse_lazy("authentication:password-change-done")


# パスワード変更完了
class CustomPasswordChangeDoneView(LoginRequiredMixin, PasswordChangeDoneView):
    """パスワード変更完了画面を表示するView。

    PasswordChangeDoneViewを継承し、パスワード変更処理が成功した場合にこのクラスで指定したtemplateを表示する。

    Attributes:
        template_name(str): 表示するtemplateまでのパスを格納する。
    """
    template_name = "authentication/password_change_done.html"


# パスワードリセット用のメール送信
class CustomPasswordResetView(PasswordResetView):
    """パスワードリセット用メールを送信するView。

    PasswordResetViewを継承し、送信先メールアドレスの入力フォームを表示する。
    メールアドレスが有効な場合、パスワードリセット用URLが記載されたメールを送信する。

    Attributes:
        template_name(str): 利用するtemplateまでのパスを格納する。
        form_class(obj): 送信先メールアドレスの入力Formを格納する。
        from_email(str): メールの送信元アドレスを指定する。
        subject_template_name(str): メールの件名のtemplateまでのパスを格納する。
        email_template_name(str): メール本文のtemplateまでのパスを格納する。
        success_url(str): メール送信が成功した場合の遷移先URLを格納する。
    """
    template_name = "authentication/password_reset.html"
    form_class = forms.CustomPasswordResetForm
    from_email = "inquiry@niwakan.mesekit.com"
    subject_template_name = "email/custom_password_reset_subject.txt"
    email_template_name = "email/custom_password_reset_email.html"
    success_url = reverse_lazy('authentication:password-reset-done')


# パスワードリセット用のメール送信完了
class CustomPasswordResetDoneView(PasswordResetDoneView):
    """パスワードリセットメール送信完了画面を表示するView。

    パスワードリセットメールの送信が成功した場合に表示するtemplateを指定する。

    Attributes:
        template_name(str): 利用するtemplateまでのパスを格納する。
    """
    template_name = "authentication/password_reset_done.html"


# パスワードリセット用URLにアクセスした際のパスワード登録
class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    """パスワードリセット時にパスワード再登録フォームを表示するView。

    メールに記載されたパスワードリセット用URLにアクセスした際にパスワード登録フォームを表示します。

    Attributes:
        template_name(str): パスワード再登録に利用するtemplateまでのパスを格納する。
        form_class(obj): パスワード再登録に利用するFormを格納する。
        success_url(str): パスワード再登録が成功した際の遷移先URLを格納する。
    """
    template_name = "authentication/password_reset_confirm.html"
    form_class = forms.CustomPasswordSetForm
    success_url = reverse_lazy("authentication:password-reset-complete")


# パスワードリセット完了
class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    """パスワードリセット完了画面を表示するView。

    PasswordResetCompleteViewを継承していますが、TemplateViewで代用可能です。
    パスワードの再登録が成功した場合に表示するtemplateを指定します。

    Attributes:
        template_name(str): 利用するtemplateまでのパスを格納します。
    """
    template_name = "authentication/password_reset_complete.html"

garden_management/authentication/templates/authentication/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ block.super }}ログイン{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block main %}
<div class="columns m-0">
    <div class="login-image column">
        <div class="login-image-text">
            <h1 class="title has-text-light has-text-centered is-3">庭の管理を簡単に。</h1>
            <p class="sub-title has-text-centered has-text-light is-size-6">
                "にわかん"は、忘れがちな水やりなどの植物の世話を<br class="br-pc">
                サポートするWEBアプリケーションです。
            </p>
        </div>
    </div>
    <div class="login-form column pb-0">
        <section class="px-6 pt-6 pb-4">
            <h1 class="title is-3">にわかん</h1>
            <h2 class="subtitle">家庭菜園支援アプリ</h2>
        </section>
        <section class="px-6 pt-4 pb-3">
            <h1 class="title is-4">ログイン</h1>
            {% if form.errors %}
            <p class="has-text-danger is-size-6">登録されているメールアドレスとパスワードが一致しませんでした。再度ご入力お願いいたします。</p>
            {% endif %}
            {% if next %}
            {% if user.is_authenticated %}
            <p class="has-text-danger is-size-6">このアカウントの持つ権限ではこのページにアクセスできません。</p>
            {% else %}
            <p class="has-text-danger is-size-6">このページにアクセスするにはログインが必要です。</p>
            {% endif %}
            {% endif %}
        </section>
        <form method="post" action="{% url 'authentication:login' %}">
            {% csrf_token %}
            <section class="px-6 pb-6">
                <div class="field mb-5">
                    <label for="" class="label">メールアドレス</label>
                    <div class="control has-icons-left">
                        {{ form.username }}
                        <span class="icon is-small is-left">
                            <i class="fas fa-envelope"></i>
                        </span>
                    </div>
                </div>
                <div class="field">
                    <label for="" class="label">パスワード</label>
                    <div class="control has-icons-left has-icons-right">
                        {{ form.password }}
                        <span class="icon is-small is-left">
                            <i class="fas fa-lock"></i>
                        </span>
                        <span class="icon is-small is-right">
                            <i class="fas fa-eye-slash" id="buttonEye" onclick="pushShowButton()"></i>
                        </span>
                    </div>
                </div>
                <a href="{% url 'authentication:password-reset' %}" id="passwordReset" tabindex="-1">
                    <span class="icon-text">
                        <span class="icon">
                            <i class="far fa-question-circle"></i>
                        </span>
                        <span>パスワードが不明の場合</span>
                    </span>
                </a>
                <section class="pt-5">
                    <div class="field">
                        <div class="control">
                            <button type="submit" class="button is-info is-outlined is-fullwidth is-login">ログイン</button>
                        </div>
                    </div>
                    <input type="hidden" name="next" value="{{ next }}">
                </section>
        </form>
        <a id="signUp" href="{% url 'authentication:signup' %}" tabindex="-1">
            <span class="icon-text">
                <span class="icon">
                    <i class="fas fa-user-plus"></i>
                </span>
                <span>新規登録はこちら</span>
            </span>
        </a>
        <!-- パスワードリセット機能を実装した際にhtmlのコメントとpythonのコメント（#）を外す。 -->
        <!-- <p><a href="{# % url "password_reset" %}">Lost password?</a></p> -->
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    function pushShowButton() {
        var txtPass = document.getElementById("id_password");
        var btnEye = document.getElementById("buttonEye");
        if (txtPass.type === "text") {
            txtPass.type = "password";
            btnEye.className = "fas fa-eye-slash";
        } else {
            txtPass.type = "text";
            btnEye.className = "fas fa-eye";
        }
    }
</script>
{% endblock %}

garden_management/authentication/templates/authentication/logout.html
{% extends "base.html" %}

{% block title %}{{ block.super }}ログアウト{% endblock %}

{% block head %}
<meta http-equiv="refresh" content=" 5; url={% url 'authentication:login' %}" />
{% endblock %}

{% block main %}
<div class="hero is-fullheight-with-navbar">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">正常にログアウトされました。</h1>
            <p class="subtitle">
                5秒後に自動的に<a class="has-text-link" href="{% url 'authentication:login' %}">ログインページ</a>へリダイレクトされます。
            </p>
        </div>
    </div>
</div>
{% endblock %}

garden_management/authentication/templates/authentication/password_change_done.html
{% extends "base.html" %}

{% block title %}{{ block.super }}パスワード変更完了{% endblock %}

{% block head %}
<meta http-equiv="refresh" content=" 10; url={% url 'plant_management:list' %}" />
{% endblock %}


{% block main %}
<div class="hero is-fullheight-with-navbar">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">変更完了</h1>
            <p class="sub-title">パスワードの変更が完了しました。</p>
            <p class="sub-title">
                10秒後に自動的に<a class="has-text-link" href="{% url 'plant_management:list' %}">一覧ページ</a>へリダイレクトされます。
            </p>
        </div>
    </div>
</div>
{% endblock %}

garden_management/authentication/templates/authentication/password_reset.html
{% extends 'base.html' %}
{% block title %}{{ block.super }}パスワードリセット{% endblock %}

{% block main %}
<div class="hero is-fullheight-with-navbar">
    <div class="container is-max-desktop">
        <section class="px-6 pt-6 pb-3">
            <h1 class="title is-3">パスワードリセット受付フォーム</h1>
            <p class="sub-title has-text-danger">
                入力されたアドレスに対してパスワードリセット用URLを送信します。
            </p>
        </section>
        <!-- form -->
        <form method="post">
            {% csrf_token %}
            <section class="px-6 pb-3">
                <p class="has-text-danger">
                    {{ form.non_field_errors }}
                </p>
            </section>
            <section class="px-6 pb-6">
                <div class="field mb-5">
                    <label for="" class="label">メールアドレス</label>
                    <div class="control has-icons-left">
                        {{ form.email }}
                        <span class="icon is-small is-left">
                            <i class="fas fa-envelope"></i>
                        </span>
                    </div>
                    <p class="help">"にわかん"に登録したメールアドレスを入力してください。</p>
                    <ul>
                        {% for error in form.email.errors %}
                        <li class="has-text-danger is-size-7">・{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </section>
            <section class="px-6 pb-6">
                <div class="field is-grouped">
                    <div class="control">
                        <button type="submit" class="button is-info is-outlined">
                            送信
                        </button>
                    </div>
                    <div class="control">
                        <button type="button" onclick="location.href=`{% url 'authentication:login' %}`"
                            class="button is-outlined">キャンセル</button>
                    </div>
                </div>
            </section>
        </form>
        <!-- END form -->
    </div>
</div>
{% endblock %}

garden_management/authentication/templates/authentication/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}{{ block.super }}パスワードリセット完了{% endblock %}

{% block main %}
<div class="hero is-fullheight-with-navbar">
    <div class="hero-body">
        <div class="container">
            <h1 class="title is-3">パスワードリセットが完了しました。</h1>
            <p class="sub-title"><a href="{% url 'authentication:login' %}">こちら</a>からログインできます。</p>
        </div>
    </div>
</div>
{% endblock %}

garden_management/authentication/templates/authentication/signup.html
{% extends "base.html" %}

{% block title %}{{ block.super }}ユーザ登録{% endblock %}

{% block main %}
<div class="hero is-fullheight-with-navbar">
    <div class="container is-max-desktop">
        <section class="px-6 pt-6 pb-3">
            <h1 class="title is-3">ユーザー登録フォーム</h1>
            <p class="sub-title has-text-danger">※全項目必須です。</p>
        </section>
        <!-- form -->
        <form method="POST">
            {% csrf_token %}
            <section class="px-6 pb-3">
                <p class="has-text-danger">
                    {{ form.non_field_errors }}
                </p>
            </section>
            <section class="px-6 pb-6">
                <h2 class="title is-4">認証情報</h2>
                <div class="field mb-5">
                    <label for="" class="label">メールアドレス</label>
                    <div class="control has-icons-left">
                        {{ form.email }}
                        <span class="icon is-small is-left">
                            <i class="fas fa-envelope"></i>
                        </span>
                    </div>
                    <p class="help">既に登録してあるメールアドレスは利用できません。</p>
                    <ul>
                        {% for error in form.email.errors %}
                        <li class="has-text-danger is-size-7">・{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="field">
                    <label for="" class="label">パスワード</label>
                    <div class="control has-icons-left has-icons-right">
                        {{ form.password1 }}
                        <span class="icon is-small is-left">
                            <i class="fas fa-lock"></i>
                        </span>
                        <span class="icon is-small is-right">
                            <i class="fas fa-eye-slash" id="buttonEye1" onclick="pushShowButton1()"></i>
                        </span>
                    </div>
                    <ul>
                        {% for error in form.password1.errors %}
                        <li class="has-text-danger is-size-7">・{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="field">
                    <label for="" class="label">パスワード（確認）</label>
                    <div class="control has-icons-left has-icons-right">
                        {{ form.password2 }}
                        <span class="icon is-small is-left">
                            <i class="fas fa-lock"></i>
                        </span>
                        <span class="icon is-small is-right">
                            <i class="fas fa-eye-slash" id="buttonEye2" onclick="pushShowButton2()"></i>
                        </span>
                    </div>
                    <p class="help">
                        パスワードは8文字以上である必要があります。半角英数記号から2種類以上組み合わせてください。
                    </p>
                    <ul>
                        {% for error in form.password2.errors %}
                        <li class="has-text-danger is-size-7">・{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </section>
            <section class="px-6 pb-6">
                <h2 class="title is-4">アカウント情報</h2>
                <div class="field mb-5">
                    <label for="" class="label">ニックネーム</label>
                    <div class="control has-icons-left">
                        {{ form.nickname }}
                        <span class="icon is-small is-left">
                            <i class="fas fa-envelope"></i>
                        </span>
                    </div>
                    <p class="help">お問い合わせの返信の際などに利用します。ニックネームは128文字未満である必要があります。</p>
                    <ul>
                        {% for error in form.nickname.errors %}
                        <li class="has-text-danger is-size-7">・{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </section>
            <section class="px-6 pb-6">
                <div class="field is-grouped">
                    <div class="control">
                        <button type="submit" class="button is-info is-outlined">
                            登録
                        </button>
                    </div>
                    <div class="control">
                        <button type="button" onclick="location.href=`{% url 'authentication:login' %}`"
                            class="button is-outlined">キャンセル</button>
                    </div>
                </div>
            </section>
        </form>
        <!-- END form -->
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    function pushShowButton1() {
        var txtPass = document.getElementById("id_password1");
        var btnEye = document.getElementById("buttonEye1");
        if (txtPass.type === "text") {
            txtPass.type = "password";
            btnEye.className = "fa fa-eye-slash";
        } else {
            txtPass.type = "text";
            btnEye.className = "fa fa-eye";
        }
    }
    function pushShowButton2() {
        var txtPass = document.getElementById("id_password2");
        var btnEye = document.getElementById("buttonEye2");
        if (txtPass.type === "text") {
            txtPass.type = "password";
            btnEye.className = "fa fa-eye-slash";
        } else {
            txtPass.type = "text";
            btnEye.className = "fa fa-eye";
        }
    }
</script>
{% endblock %}