garden_management/garden_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView

# MEDIA関連
from .settings import DEBUG, MEDIA_URL, MEDIA_ROOT
from django.contrib.staticfiles.urls import static


urlpatterns = [
    path("admin/", admin.site.urls),
    # PWA
    path(
        "sw.js", (
            TemplateView.as_view(
                template_name="sw.js", content_type="application/javascript"
            )
        ),
        name="sw.js"
    ),
    path("", RedirectView.as_view(url="/authentication/login")),
    path("authentication/", include("authentication.urls")),
    path("plant-management/", include("plant_management.urls")),
    path("help/", include("help.urls")),
]

# "settings.py"で"DEBUG=True"時のMEDIA（画像配信）の設定
if DEBUG:
    urlpatterns += static(
        MEDIA_URL, document_root=MEDIA_ROOT
    )

garden_management/help/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = "help"

urlpatterns = [
    # /helpにアクセスした場合は、お問い合わせページにリダイレクト。
    path("", RedirectView.as_view(url="/help/inquiry")),
    # 問い合わせ
    path("inquiry", views.InquiryFormView.as_view(), name="inquiry"),
    # 問い合わせ完了
    path(
        "inquiry-complete",
        views.InquiryCompleteView.as_view(),
        name="inquiry-complete"
    )
]

garden_management/plant_management/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = "plant_management"

urlpatterns = [
    # /plant-managementにアクセスした場合は、一覧ページにリダイレクト。
    path("", RedirectView.as_view(url="/plant-management/list")),
    # 植物一覧
    path("list", views.PlantListView.as_view(), name="list"),
    # 水やり完了
    path(
        "watering-complete/<int:pk>",
        views.complete_watering,
        name="watering-complete"
    ),
    # 植物詳細
    path("detail/<int:pk>", views.PlantDetailView.as_view(), name="detail"),
    # 植物追加
    path("add", views.PlantAddView.as_view(), name="add"),
    # 植物編集
    path("edit/<int:pk>", views.PlantEditView.as_view(), name="edit"),
    # 植物削除
    path("delete/<int:pk>", views.PlantDeleteView.as_view(), name="delete"),
    # 関連url追加
    path(
        "add-url/<int:plant_id>",
        views.RelatedUrlAddView.as_view(),
        name="add-url"
    ),
    # 関連url削除
    path(
        "delete-url/<int:pk>",
        views.RelatedUrlDeleteView.as_view(),
        name="delete-url"
    )
]

garden_management/plant_management/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator


class ImageCategory(models.Model):
    image_category_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = "ImageCategory"
        verbose_name_plural = "ImageCategories"

    def __str__(self):
        return self.name


class Image(models.Model):
    image_id = models.AutoField(primary_key=True)
    alt = models.CharField(max_length=255)
    path = models.ImageField(upload_to="images/")
    category = models.ForeignKey(
        ImageCategory,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = "Image"
        verbose_name_plural = "Images"

    def __str__(self):
        return self.alt


class ImageTag(models.Model):
    image_tag_id = models.AutoField(primary_key=True)
    image = models.ForeignKey(
        Image,
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = "ImageTag"
        verbose_name_plural = "ImageTags"

    def __str__(self):
        return self.name


class Plant(models.Model):
    plant_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    image = models.ForeignKey(
        Image,
        on_delete=models.SET_DEFAULT,
        default=3
    )
    watering_frequency = models.DurationField(
        default=datetime.timedelta(days=1)
    )
    last_watering_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(max_length=4095, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    priority = models.PositiveSmallIntegerField()
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = "Plant"
        verbose_name_plural = "Plants"

    def __str__(self):
        return self.name


class RelatedURL(models.Model):
    related_url_id = models.AutoField(primary_key=True)
    plant = models.ForeignKey(
        Plant,
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=2047)
    url = models.URLField(max_length=2047)
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = "RelatedURL"
        verbose_name_plural = "RelatedURLs"

    def __str__(self):
        return self.url


class Color(models.Model):
    color_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    color_code = models.PositiveIntegerField(
        validators=(MaxValueValidator(16777215),)
    )

    class Meta:
        verbose_name = "Color"
        verbose_name_plural = "Colors"

    def __str__(self):
        return self.name


class CultivationCalendar(models.Model):
    cultivation_calendar_id = models.AutoField(primary_key=True)
    plant = models.ForeignKey(
        Plant,
        on_delete=models.CASCADE
    )
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=4095, blank=True, null=True)
    color = models.ForeignKey(
        Color,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    start_at = models.PositiveSmallIntegerField(
        validators=(MaxValueValidator(35),)
    )
    end_at = models.PositiveSmallIntegerField(
        validators=(MaxValueValidator(35),)
    )
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = "CultivationCalendar"
        verbose_name_plural = "CultibationCalendars"

    def __str__(self):
        return self.title

garden_management/plant_management/forms.py
from django import forms
from .models import Plant, Image, RelatedURL


# 植物追加フォーム。
class AddPlantForm(forms.ModelForm):
    class Meta:
        model = Plant
        fields = (
            "name",
            "image",
            "watering_frequency",
            "last_watering_date",
            "description",
            "priority"
        )

    name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(
            attrs={
                "class": "input",
                "placeholder": "バラ"
            }
        )
    )

    image = forms.ModelChoiceField(
        queryset=Image.objects.order_by("pk"),
        empty_label="選択してください。"
    )

    watering_frequency = forms.DurationField(
        widget=forms.TimeInput(
            attrs={
                "class": "input",
                "placeholder": "1 00:00:00"
            }
        )
    )

    last_watering_date = forms.DateTimeField(
        widget=forms.DateTimeInput(
            attrs={
                "class": "input",
                "type": "datetime-local"
            }
        )
    )

    description = forms.CharField(
        required=False,
        max_length=4095,
        widget=forms.Textarea(
            attrs={
                "class": "textarea",
                "placeholder": (
                    "バラ（薔薇）は、バラ科バラ属の総称である[1][要ページ番号][2][要ページ番号][3][要ページ番号]。"
                    "あるいは、そのうち特に園芸種（園芸バラ・栽培バラ）を総称する[1]（花が鑑賞用や食用とされる[4] ）。"
                    "本項では、後者の園芸バラ・栽培バラを扱うこととする。\n"
                    "wikipedia「バラ」より引用。"
                )
            }
        )
    )

    priority = forms.IntegerField(
        min_value=0,
        max_value=32767,
        widget=forms.NumberInput(
            attrs={
                "class": "input",
                "placeholder": "0 ~ 32767"
            }
        )
    )


# 植物編集フォーム。
class EditPlantForm(forms.ModelForm):
    class Meta:
        model = Plant
        fields = (
            "name",
            "image",
            "watering_frequency",
            "last_watering_date",
            "description",
            "priority"
        )

    name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(
            attrs={
                "class": "input",
                "placeholder": "バラ"
            }
        )
    )

    image = forms.ModelChoiceField(
        queryset=Image.objects.order_by("pk"),
        empty_label="選択してください。"
    )

    watering_frequency = forms.DurationField(
        widget=forms.TimeInput(
            attrs={
                "class": "input",
                "placeholder": "1 00:00:00"
            }
        )
    )

    last_watering_date = forms.DateTimeField(
        widget=forms.DateTimeInput(
            attrs={
                "class": "input",
                "type": "datetime-local"
            }
        )
    )

    description = forms.CharField(
        required=False,
        max_length=4095,
        widget=forms.Textarea(
            attrs={
                "class": "textarea",
                "placeholder": (
                    "バラ（薔薇）は、バラ科バラ属の総称である[1][要ページ番号][2][要ページ番号][3][要ページ番号]。"
                    "あるいは、そのうち特に園芸種（園芸バラ・栽培バラ）を総称する[1]（花が鑑賞用や食用とされる[4] ）。"
                    "本項では、後者の園芸バラ・栽培バラを扱うこととする。\n"
                    "wikipedia「バラ」より引用。"
                )
            }
        )
    )

    priority = forms.IntegerField(
        min_value=0,
        max_value=32767,
        widget=forms.NumberInput(
            attrs={
                "class": "input",
                "placeholder": "0 ~ 32767"
            }
        )
    )


# 関連URL追加フォーム。
class AddRelatedUrlForm(forms.ModelForm):
    class Meta:
        model = RelatedURL
        fields = (
            "name",
            "url"
        )

    name = forms.CharField(
        max_length=2047,
        widget=forms.TextInput(
            attrs={
                "class": "input",
                "placeholder": "サイト名など"
            }
        )
    )

    url = forms.URLField(
        max_length=2047,
        widget=forms.URLInput(
            attrs={
                "class": "input",
                "placeholder": "niwakan.mesekit.com"
            }
        )
    )

garden_management/plant_management/views.py
import datetime
from . import forms
from . import mixins
from .models import Plant, RelatedURL
from .functions import get_watering_state
from utilities.mixins import OwnerOnlyMixin
from django.views import generic
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin


# 植物一覧（水やり状態）
class PlantListView(LoginRequiredMixin, generic.ListView):
    model = Plant
    template_name = "plant_management/plant_list.html"
    context_object_name = "plants"

    # 取得するデータをカスタマイズする。
    def get_queryset(self):
        # .filter()：ユーザが作成したオブジェクトのみ取り出す。
        # .order_by()：priorityの値で降順ソートした後、plant_idで昇順ソートする。
        queryset = self.model.objects \
            .select_related("image") \
            .values("plant_id", "name", "description",
                    "image__path", "image__alt", "last_watering_date",
                    "watering_frequency", "priority") \
            .filter(user=self.request.user) \
            .order_by("-priority", "plant_id")
        return queryset

    # 水やりの状態（水やりの要否・次回の水やりまでの時間）を保存するcontextを追加する。
    def get_context_data(self, **kwargs):
        # 継承元（ListView）のget_context_dataを呼んで、contextを取得。
        context = super().get_context_data(**kwargs)
        plants = context["plants"]
        for plant in plants:
            plant["watering_state"] = get_watering_state(
                plant["last_watering_date"], plant["watering_frequency"]
            )
        context["plants"] = plants
        return context


# 水やり完了処理
def complete_watering(request, pk):
    plant = Plant.objects.get(pk=pk)
    if plant.user != request.user:
        try:
            raise PermissionDenied()
        except PermissionDenied:
            print("You do not have permission to edit.")
            return redirect("authentication:login")
    plant.last_watering_date = datetime.datetime.now()
    plant.save()
    if request.headers.get("X-Requested-With") == "XMLHttpRequest":
        data = {
            "watering-state": get_watering_state(
                plant.last_watering_date, plant.watering_frequency
            )
        }
    return JsonResponse(data)


# 植物詳細
class PlantDetailView(
    OwnerOnlyMixin, LoginRequiredMixin, generic.DetailView
):
    model = Plant
    template_name = "plant_management/plant_detail.html"
    context_object_name = "plant_detail"

    # 水やりの状態（水やりの要否・次回の水やりまでの時間）を保存するcontextを追加する。
    def get_context_data(self, **kwargs):
        # 継承元（DetailView）のget_context_dataを呼んで、contextを取得。
        context = super().get_context_data(**kwargs)
        plant = context["plant_detail"]
        context["watering_state"] = get_watering_state(
            plant.last_watering_date, plant.watering_frequency
        )
        return context


# 植物追加
class PlantAddView(LoginRequiredMixin, generic.CreateView):
    form_class = forms.AddPlantForm
    template_name = "plant_management/plant_add.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            "plant_management:detail", kwargs={"pk": self.object.plant_id}
        )


# 植物編集
class PlantEditView(
    mixins.PlantOwnerOnlyMixin, LoginRequiredMixin, generic.UpdateView
):
    model = Plant
    form_class = forms.EditPlantForm
    template_name = "plant_management/plant_edit.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        plant = Plant.objects.get(pk=self.kwargs["pk"])
        context["plant_name"] = plant.name
        return context

    def get_success_url(self):
        return reverse_lazy(
            "plant_management:detail", kwargs={"pk": self.object.plant_id}
        )


# 植物削除
class PlantDeleteView(
    mixins.PlantOwnerOnlyMixin, LoginRequiredMixin, generic.DeleteView
):
    template_name = "plant_management/plant_delete.html"
    model = Plant
    success_url = reverse_lazy("plant_management:list")


# 関連URL追加
class RelatedUrlAddView(
    mixins.RelatedPlantOwnerOnlyMixin, LoginRequiredMixin, generic.CreateView
):
    form_class = forms.AddRelatedUrlForm
    template_name = "plant_management/related_url_add.html"

    def form_valid(self, form):
        plant = Plant.objects.get(pk=self.kwargs.get("plant_id"))
        form.instance.user = self.request.user
        form.instance.plant = plant
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        plant = Plant.objects.get(pk=self.kwargs.get("plant_id"))
        context["plant_name"] = plant.name
        return context

    def get_success_url(self):
        return reverse_lazy(
            "plant_management:detail", kwargs={"pk": self.object.plant_id}
        )


# 関連URL削除
class RelatedUrlDeleteView(
    OwnerOnlyMixin, LoginRequiredMixin, generic.DeleteView
):
    template_name = "plant_management/related_url_delete.html"
    model = RelatedURL
    context_object_name = "url_info"

    def get_success_url(self):
        return reverse_lazy(
            "plant_management:detail", kwargs={"pk": self.object.plant_id}
        )

garden_management/plant_management/templates/plant_management/plant_delete.html
{% extends "base.html" %}

{% block title %}{{ block.super }}削除確認{% endblock %}

{% block main %}
<div class="hero is-fullheight-with-navbar">
    <div class="hero-body">
        <div class="container is-max-desktop">
            <form method="post">
                {% csrf_token %}
                <h1 class="title">「{{ object }}」を削除しようとしています。</h1>
                <h3 class="subtitle has-text-danger mb-0 mt-5">削除した植物は元に戻すことはできません。</h3>
                <h3 class="subtitle">削除する場合は確定ボタンを押してください。</h3>
                <button class="button is-info is-outlined" type="submit">確定</button>
                <button type="button" class="button is-outlined"
                    onclick="location.href=`{% url 'plant_management:detail' pk=object.plant_id %}`">キャンセル</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

garden_management/plant_management/templates/plant_management/plant_detail.html
{% extends "base.html" %}

{% block head %}
<script src="https://code.jquery.com/jquery-3.7.1.min.js"
    integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
{% endblock %}

{% block title %}{{ block.super }}植物詳細{% endblock %}

{% block main %}
<div class="hero is-fullheight-with-navbar">
    <div class="hero-body">
        <div class="container is-max-desktop">
            <section class="pb-3">
                <h1 class="title is-3">{{ plant_detail.name }}</h1>
                <div id="plant-image-container">
                    <img id="plant-image" src="/media/{{ plant_detail.image.path }}" alt="{{ plant_detail.image.alt }}">
                </div>
            </section>
            <section>
                <h2 class="title is-4 mb-0">説明</h2>
                <p class="pb-5">{{ plant_detail.description|linebreaksbr }}</p>
                <h2 class="title is-4 mb-0">関連URL</h2>
                <!-- ForeignKeyを逆参照して関連するurlを取得。 -->
                {% if plant_detail.relatedurl_set.all.0 is None %}
                <p>関連URLは存在しません。</p>
                {% endif %}
                {% for url in plant_detail.relatedurl_set.all %}
                <div class="related-url-container">
                    <span class="related-url">
                        <a href="{{ url.url }}" target="_blank">{{ url.name }}</a> | {{ url.url }}
                    </span>
                    <button type="button"
                        onclick="location.href=`{% url 'plant_management:delete-url' pk=url.related_url_id %}`"
                        class="button is-danger is-outlined delete-related-url-button">
                        <span class="icon">
                            <i class="fas fa-trash"></i>
                        </span>
                    </button>
                </div>
                {% endfor %}
                <button onclick="location.href=`{% url 'plant_management:add-url' plant_id=plant_detail.plant_id %}`"
                    type="button" class="button is-primary is-outlined">
                    <span class="icon-text">
                        <span class="icon">
                            <i class="fas fa-plus"></i>
                        </span>
                        <span>関連URLの追加</span>
                    </span>
                </button>
                <div class="mb-5"></div>
                <h2 class="title is-4 mb-0">水やり頻度</h2>
                <p class="pb-5">{{ plant_detail.watering_frequency }}</p>
                <h2 class="title is-4 mb-0">最後に水やりをした日時</h2>
                <p class="pb-5">{{ plant_detail.last_watering_date }}</p>
                <h2 class="title is-4 mb-1">水やり</h2>
                <!-- completed watering button -->
                {% if watering_state.required is False %}
                <button disabled class="button is-dark is-fullwidth is-rounded is-outlined detail-watering-button"
                    data-id="{{ plant_detail.plant_id }}">
                    <span class="has-icon-left">
                        <span class="icon has-text-info">
                            <i class="fas fa-tint"></i>
                        </span>
                        {{ watering_state.message }}
                    </span>
                </button>
                {% endif %}
                <!-- END completed watering button -->
                <!-- watering button -->
                {% if watering_state.required %}
                {% csrf_token %}
                <button
                    class="toggle-watering-complete button is-info is-fullwidth is-rounded is-outlined detail-watering-button"
                    data-id="{{ plant_detail.plant_id }}">
                    <span class="has-icon-left">
                        <span class="icon has-text-info">
                            <i class="fas fa-tint"></i>
                        </span>
                        {{ watering_state.message }}
                    </span>
                </button>
                {% endif %}
                <!-- END watering button -->
                <div class="mb-5"></div>
                <h2 class="title is-4 mb-0">表示優先度</h2>
                <h3 class="sub-title mb-0 has-text-grey-light">※数値が高いほど上位に表示されます。(0~32767)</h3>
                <p class="pb-5">{{ plant_detail.priority }}</p>
            </section>
            <div class="field is-grouped">
                <p class="control">
                    <button type="button" onclick="location.href=`{% url 'plant_management:list' %}`"
                        class="button is-outlined">
                        <span class="icon-text">
                            <span class="icon">
                                <i class="far fa-list-alt"></i>
                            </span>
                            <span>
                                一覧
                            </span>
                        </span>
                    </button>
                </p>
                <p class="control">
                    <button type="button"
                        onclick="location.href=`{% url 'plant_management:edit' pk=plant_detail.plant_id %}`"
                        class="button is-info is-outlined">
                        <span class="icon-text">
                            <span class="icon">
                                <i class="fas fa-edit"></i>
                            </span>
                            <span>
                                編集
                            </span>
                        </span>
                    </button>
                </p>
                <p class="control">
                    <button type="button"
                        onclick="location.href=`{% url 'plant_management:delete' pk=plant_detail.plant_id %}`"
                        class="button is-danger is-outlined">
                        <span class="icon-text">
                            <span class="icon">
                                <i class="fas fa-trash"></i>
                            </span>
                            <span>
                                削除
                            </span>
                        </span>
                    </button>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    //完了、未完了ボタンを押したときの動き
    $(document).ready(function () {
        $(".toggle-watering-complete").click(function () {
            //1.plantID取得
            var plantId = $(this).data("id");
            //2,Ajax送信処理
            $.ajax({
                url: "/plant-management/watering-complete/" + plantId,
                type: "POST",
                dataType: "json",
                //3.CSRF処理
                beforeSend: function (xhr, settings) {
                    xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
                    xhr.setRequestHeader("X-CSRFToken", $("input[name='csrfmiddlewaretoken']").val());
                },
                //4.Ajax受信処理
                success: function (data, textStatus, xhr) {
                    var elem = $(`button[data-id=${plantId}]`);
                    elem.replaceWith(
                        `<button disabled class="button is-dark is-rounded is-outlined"
                        data-id=${plantId}>
                        <span class="has-icon-left">
                            <span class="icon has-text-info">
                                <i class="fas fa-tint"></i>
                            </span>
                            ${data["watering-state"]["message"]}
                        </span>
                    </button>`
                    );
                },
            });
        });
    });
</script>
{% endblock %}

garden_management/plant_management/templates/plant_management/plant_list.html
{% extends "base.html" %}

{% block head %}
<script src="https://code.jquery.com/jquery-3.7.1.min.js"
    integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
{% endblock %}

{% block title %}{{ block.super }}一覧{% endblock %}

{% block main %}
<div class="hero is-fullheight-with-navbar pt-6">
    <div class="table-container mb-6">
        <h1 class="title">植物一覧</h1>
        <button onclick="location.href=`{% url 'plant_management:add' %}`" type="button"
            class="button is-primary is-outlined mb-2">
            <span class="test-icon">
                <span class="icon"><i class="fas fa-plus"></i></span>
                <span>植物追加</span>
            </span>
        </button>
        <table class="table is-bordered is-hoverable is-fullwidth plant-list">
            <tbody>
                {% for p in plants %}
                <tr>
                    <td class="plant-list-image"><img src="/media/{{ p.image__path }}" alt="{{ p.image__alt }}">
                    </td>
                    <td>
                        <a class="detail-link" href="{% url 'plant_management:detail' pk=p.plant_id %}">
                            <div>
                                {{ p.name }}
                                <p class="has-text-grey-light plant-description"><small>{{ p.description }}</small></p>
                                <p class="has-text-grey-light plant-description"><small>表示優先度：{{ p.priority }}</small>
                                </p>
                            </div>
                        </a>
                    </td>
                    <td class="plant-list-watering">
                        <!-- completed watering button -->
                        {% if p.watering_state.required is False %}
                        <button disabled class="button is-dark is-fullwidth is-rounded is-outlined"
                            data-id="{{ p.plant_id }}">
                            <span class="has-icon-left">
                                <span class="icon has-text-info">
                                    <i class="fas fa-tint"></i>
                                </span>
                                {{ p.watering_state.message }}
                            </span>
                        </button>
                        {% endif %}
                        <!-- END completed watering button -->
                        <!-- watering button -->
                        {% if p.watering_state.required %}
                        {% csrf_token %}
                        <button class="toggle-watering-complete button is-info is-fullwidth is-rounded is-outlined"
                            data-id="{{ p.plant_id }}">
                            <span class="has-icon-left">
                                <span class="icon has-text-info">
                                    <i class="fas fa-tint"></i>
                                </span>
                                {{ p.watering_state.message }}
                            </span>
                        </button>
                        {% endif %}
                        <!-- END watering button -->
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    //完了、未完了ボタンを押したときの動き
    $(document).ready(function () {
        $(".toggle-watering-complete").click(function () {
            //1.plantID取得
            var plantId = $(this).data("id");
            //2,Ajax送信処理
            $.ajax({
                url: "/plant-management/watering-complete/" + plantId,
                type: "POST",
                dataType: "json",
                //3.CSRF処理
                beforeSend: function (xhr, settings) {
                    xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
                    xhr.setRequestHeader("X-CSRFToken", $("input[name='csrfmiddlewaretoken']").val());
                },
                //4.Ajax受信処理
                success: function (data, textStatus, xhr) {
                    var elem = $(`button[data-id=${plantId}]`);
                    elem.replaceWith(
                        `<button disabled class="button is-dark is-fullwidth is-rounded is-outlined"
                        data-id=${plantId}>
                        <span class="has-icon-left">
                            <span class="icon has-text-info">
                                <i class="fas fa-tint"></i>
                            </span>
                            ${data["watering-state"]["message"]}
                        </span>
                    </button>`
                    );
                },
            });
        });
    });
</script>
{% endblock %}

garden_management/plant_management/templates/plant_management/related_url_delete.html
{% extends "base.html" %}

{% block title %}{{ block.super }}関連URL削除{% endblock %}

{% block main %}
<div class="hero is-fullheight-with-navbar">
    <div class="hero-body">
        <div class="container is-max-desktop">
            <form method="post">
                {% csrf_token %}
                <h1 class="title">「{{ url_info.name }} | {{ url_info.url }}」を削除しようとしています。</h1>
                <h3 class="subtitle has-text-danger mb-0 mt-5">削除したURLは元に戻すことはできません。</h3>
                <h3 class="subtitle">削除する場合は確定ボタンを押してください。</h3>
                <button class="button is-info is-outlined" type="submit">確定</button>
                <button type="button" class="button is-outlined"
                    onclick="location.href=`{% url 'plant_management:detail' pk=object.plant_id %}`">キャンセル</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}